// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/baremetalsolution/v2/baremetalsolution.proto

package com.google.cloud.baremetalsolution.v2;

public interface CreateSnapshotSchedulePolicyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.baremetalsolution.v2.CreateSnapshotSchedulePolicyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The parent project and location containing the SnapshotSchedulePolicy.
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * Required. The parent project and location containing the SnapshotSchedulePolicy.
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <pre>
   * Required. The SnapshotSchedulePolicy to create.
   * </pre>
   *
   * <code>.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy snapshot_schedule_policy = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the snapshotSchedulePolicy field is set.
   */
  boolean hasSnapshotSchedulePolicy();
  /**
   * <pre>
   * Required. The SnapshotSchedulePolicy to create.
   * </pre>
   *
   * <code>.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy snapshot_schedule_policy = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The snapshotSchedulePolicy.
   */
  com.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy getSnapshotSchedulePolicy();
  /**
   * <pre>
   * Required. The SnapshotSchedulePolicy to create.
   * </pre>
   *
   * <code>.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy snapshot_schedule_policy = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicyOrBuilder getSnapshotSchedulePolicyOrBuilder();

  /**
   * <pre>
   * Required. Snapshot policy ID
   * </pre>
   *
   * <code>string snapshot_schedule_policy_id = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The snapshotSchedulePolicyId.
   */
  java.lang.String getSnapshotSchedulePolicyId();
  /**
   * <pre>
   * Required. Snapshot policy ID
   * </pre>
   *
   * <code>string snapshot_schedule_policy_id = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for snapshotSchedulePolicyId.
   */
  com.google.protobuf.ByteString
      getSnapshotSchedulePolicyIdBytes();
}
