// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/baremetalsolution/v2/baremetalsolution.proto

package com.google.cloud.baremetalsolution.v2;

public interface SnapshotSchedulePolicyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Output only. The name of the snapshot schedule policy.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Output only. The name of the snapshot schedule policy.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The description of the snapshot schedule policy.
   * </pre>
   *
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * The description of the snapshot schedule policy.
   * </pre>
   *
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * The snapshot schedules contained in this policy. You can specify a maximum
   *  of 5 schedules.
   * </pre>
   *
   * <code>repeated .google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy.Schedule schedules = 3;</code>
   */
  java.util.List<com.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy.Schedule> 
      getSchedulesList();
  /**
   * <pre>
   * The snapshot schedules contained in this policy. You can specify a maximum
   *  of 5 schedules.
   * </pre>
   *
   * <code>repeated .google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy.Schedule schedules = 3;</code>
   */
  com.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy.Schedule getSchedules(int index);
  /**
   * <pre>
   * The snapshot schedules contained in this policy. You can specify a maximum
   *  of 5 schedules.
   * </pre>
   *
   * <code>repeated .google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy.Schedule schedules = 3;</code>
   */
  int getSchedulesCount();
  /**
   * <pre>
   * The snapshot schedules contained in this policy. You can specify a maximum
   *  of 5 schedules.
   * </pre>
   *
   * <code>repeated .google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy.Schedule schedules = 3;</code>
   */
  java.util.List<? extends com.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy.ScheduleOrBuilder> 
      getSchedulesOrBuilderList();
  /**
   * <pre>
   * The snapshot schedules contained in this policy. You can specify a maximum
   *  of 5 schedules.
   * </pre>
   *
   * <code>repeated .google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy.Schedule schedules = 3;</code>
   */
  com.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy.ScheduleOrBuilder getSchedulesOrBuilder(
      int index);
}
