// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/baremetalsolution/v2/baremetalsolution.proto

package com.google.cloud.baremetalsolution.v2;

public interface UpdateSnapshotSchedulePolicyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.baremetalsolution.v2.UpdateSnapshotSchedulePolicyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The snapshot schedule policy to update.
   * The `name` field is used to identify the snapshot schedule policy to
   * update. Format:
   * projects/{project}/locations/global/snapshotSchedulePolicies/{policy}
   * </pre>
   *
   * <code>.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy snapshot_schedule_policy = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the snapshotSchedulePolicy field is set.
   */
  boolean hasSnapshotSchedulePolicy();
  /**
   * <pre>
   * Required. The snapshot schedule policy to update.
   * The `name` field is used to identify the snapshot schedule policy to
   * update. Format:
   * projects/{project}/locations/global/snapshotSchedulePolicies/{policy}
   * </pre>
   *
   * <code>.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy snapshot_schedule_policy = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The snapshotSchedulePolicy.
   */
  com.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy getSnapshotSchedulePolicy();
  /**
   * <pre>
   * Required. The snapshot schedule policy to update.
   * The `name` field is used to identify the snapshot schedule policy to
   * update. Format:
   * projects/{project}/locations/global/snapshotSchedulePolicies/{policy}
   * </pre>
   *
   * <code>.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicy snapshot_schedule_policy = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.baremetalsolution.v2.SnapshotSchedulePolicyOrBuilder getSnapshotSchedulePolicyOrBuilder();

  /**
   * <pre>
   * Required. The list of fields to update.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the updateMask field is set.
   */
  boolean hasUpdateMask();
  /**
   * <pre>
   * Required. The list of fields to update.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The updateMask.
   */
  com.google.protobuf.FieldMask getUpdateMask();
  /**
   * <pre>
   * Required. The list of fields to update.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();
}
