// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/baremetalsolution/v2/baremetalsolution.proto

package com.google.cloud.baremetalsolution.v2;

public interface VolumeSnapshotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.baremetalsolution.v2.VolumeSnapshot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Output only. The name of the storage volume snapshot.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Output only. The name of the storage volume snapshot.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The description of the storage volume snapshot.
   * </pre>
   *
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * The description of the storage volume snapshot.
   * </pre>
   *
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * The size of the storage volume snapshot, in bytes.
   * </pre>
   *
   * <code>int64 size_bytes = 3;</code>
   * @return The sizeBytes.
   */
  long getSizeBytes();

  /**
   * <pre>
   * Optional. The creation time of the storage volume snapshot.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <pre>
   * Optional. The creation time of the storage volume snapshot.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <pre>
   * Optional. The creation time of the storage volume snapshot.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <pre>
   * The storage volume this snapshot belongs to.
   * </pre>
   *
   * <code>string storage_volume = 5 [(.google.api.resource_reference) = { ... }</code>
   * @return The storageVolume.
   */
  java.lang.String getStorageVolume();
  /**
   * <pre>
   * The storage volume this snapshot belongs to.
   * </pre>
   *
   * <code>string storage_volume = 5 [(.google.api.resource_reference) = { ... }</code>
   * @return The bytes for storageVolume.
   */
  com.google.protobuf.ByteString
      getStorageVolumeBytes();
}
